-- 06.	University Database
CREATE TABLE Subjects
(
	SubjectID INT PRIMARY KEY IDENTITY,
	SubjectName NVARCHAR(50) NOT NULL
)

CREATE TABLE Majors
(
	MajorID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Students
(
	StudentID INT PRIMARY KEY IDENTITY,
	StudentNumber INT NOT NULL,
	StudentName NVARCHAR(50) NOT NULL,
	MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
	PaymentID INT PRIMARY KEY IDENTITY,
	PaymentDate DATETIME2 NOT NULL,
	PaymentAmount DECIMAL(10, 2) NOT NULL,
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Agenda
(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL
)

ALTER TABLE Agenda
ADD CONSTRAINT KK_StudentsID_SubjectsID
PRIMARY KEY(StudentID, SubjectID)

ALTER TABLE Agenda
ADD CONSTRAINT FK_StudentsID
FOREIGN KEY (StudentID) REFERENCES Students(StudentID)

ALTER TABLE Agenda
ADD CONSTRAINT FK_SubjectsID
FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)