CREATE TABLE Countries
(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   [Name] NVARCHAR(100)
)

CREATE TABLE Towns
(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   [Name] NVARCHAR(100),
   CountryCode INT FOREIGN KEY REFERENCES Countries(Id)
)

CREATE TABLE Minions
(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   [Name] NVARCHAR(100) NOT NULL,
   Age INT,
   TownId INT FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE EvilnessFactors
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(100)
)

CREATE TABLE Villains
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(100),
EvilnessFactorId INT FOREIGN KEY REFERENCES EvilnessFactors(Id)
)

CREATE TABLE MinionsVillains
(
	MinionId INT NOT NULL,
	VillainId INT NOT NULL
)

ALTER TABLE MinionsVillains
ADD CONSTRAINT PK_MinionId_VillainId
PRIMARY KEY(MinionId, VillainId)

ALTER TABLE MinionsVillains
ADD CONSTRAINT FK_MinionId
FOREIGN KEY(MinionId) REFERENCES Minions(Id)

ALTER TABLE MinionsVillains
ADD CONSTRAINT FK_VillainId
FOREIGN KEY(VillainId) REFERENCES Villains(Id)