CREATE TABLE Majors
(
	MajorID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50)
)
--
CREATE TABLE Students
(
	StudentID INT NOT NULL PRIMARY KEY,
	StudentNumber INT NOT NULL,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorID)
)
--
CREATE TABLE Payments
(
	PaymentID INT NOT NULL PRIMARY KEY,
	PaymentDate DATETIME NOT NULL,
	PaymentAmount DECIMAL(15, 2) NOT NULL,
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID)
)
--
CREATE TABLE Subjects
(
	SubjectID INT NOT NULL PRIMARY KEY,
	SubjectName VARCHAR(50) NOT NULL
)
--
CREATE TABLE Agenda
(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL
)
--
ALTER TABLE Agenda
ADD CONSTRAINT KK_StudentID_SubjectID
PRIMARY KEY(StudentID, SubjectID)
--
ALTER TABLE Agenda
ADD CONSTRAINT FK_StudentID
FOREIGN KEY(StudentID) REFERENCES Students(StudentID)
--
ALTER TABLE Agenda
ADD CONSTRAINT FK_SubjectID
FOREIGN KEY(SubjectID) REFERENCES Subjects(SubjectID)
