CREATE TABLE Cities
(
	CityID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50)
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50)
)
--
CREATE TABLE Items
(
	ItemID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50),
	ItemTypeID INT NOT NULL FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)
--
CREATE TABLE Customers
(
	CustomerID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT NOT NULL FOREIGN KEY REFERENCES Cities(CityID)
)
--
CREATE TABLE Orders
(
	OrderID INT NOT NULL PRIMARY KEY, -- Евентуално UNIQUE
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers(CustomerID)
)
--
CREATE TABLE OrderItems
(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
)

ALTER TABLE OrderItems
ADD CONSTRAINT KK_OrderID_ItemID
PRIMARY KEY(OrderID, ItemID)
--
ALTER TABLE OrderItems
ADD CONSTRAINT FK_OrderID
FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)
--
ALTER TABLE OrderItems
ADD CONSTRAINT FK_ItemID
FOREIGN KEY(ItemID) REFERENCES Items(ItemID)